global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: wukongim-trace-metrics
    static_configs:
    - targets: ['192.168.3.82:5001','192.168.3.82:5002','192.168.3.82:5003']